### ISSUE TITLE
How is this addon used?

### ISSUE THREAD

**Issue by thany** [wavebeem/url-redirect-webextension#9]
Please provide instructions on how to configure redirects. I can't seem to find anything anywhere that allows me to add a redirect, so this requires explanation. Either here or on Mozilla, or both.

Or alternatively, add a config option somewhere in the devtools. Or in the addon manager. Or somewhere slightly obvious.

**Comment by wavebeem** [comment]
Hi @thany, you can click the URL Redirect icon to open the settings page

![image](https://user-images.githubusercontent.com/176815/127683222-60cd0afc-d54b-4980-8d7e-125c89065d57.png)

This page contains examples and configuration.

![image](https://user-images.githubusercontent.com/176815/127683292-ddef6505-3565-41f2-b85e-c0935745ff23.png)
